version: '3.8'
services:
  #  app:
  #    container_name: skillswap-backend
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    ports:
  #      - "3000:3000"
  #    depends_on:
  #      - db
  #    environment:
  #      DATABASE_HOST: db
  #      DATABASE_USER: root
  #      DATABASE_PASSWORD: root
  #      DATABASE_NAME: skillswap

  db:
    container_name: mysql-db
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skillswap
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
