export const skillSeed = [
  { name: 'Cooking' },
  { name: 'Baking' },
  { name: 'Studying' },
  { name: 'Public Speaking' },
  { name: 'Personal Finance' },
  { name: 'Programming' },
  { name: 'Writing' },
  { name: 'Foreign Languages' },
  { name: 'Fitness' },
  { name: 'Photography' },
  { name: 'Graphic Design' },
  { name: 'Time Management' },
  { name: 'Dance' },
  { name: 'Music' },
  { name: 'Crafts' },
  { name: 'Social Media' },
  { name: 'Academic Tutoring' },
  { name: 'Home Repair' },
  { name: 'Car Maintenance' },
  { name: 'Mindfulness' },
  { name: 'Board Games' },
  { name: 'Gardening' },
  { name: 'Digital Marketing' },
  { name: 'Leadership' },
  { name: 'Art' },
  { name: 'Event Planning' },
  { name: 'Video Production' },
  { name: 'Environmental Awareness' },
  { name: 'Networking' },
  { name: 'Career Preparation' },
  { name: 'Fashion' },
  { name: 'Illustration' },
  { name: 'Technology' },
  { name: 'Travel' },
  { name: 'Outdoor Skills' },
  { name: 'Sports' },
  { name: 'Nutrition' },
  { name: 'Cultural Studies' },
  { name: 'Sustainability' },
  { name: 'Community Service' },
  { name: 'Investing' },
  { name: 'Performing Arts' },
  { name: 'Debate' },
  { name: 'Entrepreneurship' },
  { name: 'Content Creation' },
  { name: 'Wellness' },
];
