// src/services/courses/courses.service.ts

import { Injectable } from '@nestjs/common';

@Injectable()
export class CoursesService {
  private readonly courses = [
    'UNDERGRADUATE COURSES',
    'Accounting (BSc)',
    'Accounting and Finance (BAEcon)',
    'Accounting with Industrial/Professional Experience (BSc)',
    'Actuarial Science and Mathematics (BSc)',
    'Adult Nursing (BNurs)',
    'Aerospace Engineering (BEng)',
    'Aerospace Engineering (MEng)',
    'Aerospace Engineering with Industrial Experience (MEng)',
    'Aerospace Engineering with Management (MEng)',
    'American Studies (BA)',
    'Ancient History (BA)',
    'Ancient History and Archaeology (BA)',
    'Ancient History and History (BA)',
    'Arabic and French (BA)',
    'Arabic and German (BA)',
    'Arabic and Italian (BA)',
    'Arabic and Politics (BA)',
    'Arabic and Portuguese (BA)',
    'Arabic and Russian (BA)',
    'Arabic and Spanish (BA)',
    'Arabic Studies (BA)',
    'Archaeology (BA)',
    'Archaeology and Ancient History (BA)',
    'Archaeology and Anthropology (BA)',
    'Archaeology and History (BA)',
    'Architecture (BA)',
    'Architecture with Foundation Year (BA)',
    'Art History and Arabic (BA)',
    'Art History and Chinese (BA)',
    'Art History and English Literature (BA)',
    'Art History and French (BA)',
    'Art History and German (BA)',
    'Art History and History (BA)',
    'Art History and Italian (BA)',
    'Art History and Japanese (BA)',
    'Art History and Portuguese (BA)',
    'Art History and Russian (BA)',
    'Art History and Spanish (BA)',
    'Biochemistry (BSc)',
    'Biochemistry (MSci)',
    'Biochemistry with a Modern Language (BSc)',
    'Biochemistry with Entrepreneurship (BSc)',
    'Biochemistry with Industrial/Professional Experience (BSc)',
    'Biology (BSc)',
    'Biology (MSci)',
    'Biology with a Modern Language (BSc)',
    'Biology with Entrepreneurship (BSc)',
    'Biology with Industrial/Professional Experience (BSc)',
    'Biology with Science & Society (BSc)',
    'Biology with Science and Society with Industrial/Professional Experience (BSc)',
    'Biomedical Sciences (BSc)',
    'Biomedical Sciences (MSci)',
    'Biomedical Sciences with a Modern Language (BSc)',
    'Biomedical Sciences with Entrepreneurship (BSc)',
    'Biomedical Sciences with Industrial/Professional Experience (BSc)',
    'Biosciences with a Foundation Year',
    'Biotechnology (BSc)',
    'Biotechnology (MSci)',
    'Biotechnology with Entrepreneurship (BSc)',
    'Biotechnology with Industrial/Professional Experience (BSc)',
    'Business Accounting with Industrial/Professional Experience (BSc)',
    'Chemical Engineering (BEng)',
    'Chemical Engineering (MEng)',
    'Chemical Engineering with Energy and Environment (MEng)',
    'Chemical Engineering with Industrial Experience (MEng)',
    'Chemical Engineering with Study in Europe (MEng)',
    'Chemistry (BSc)',
    'Chemistry (MChem)',
    'Chemistry with Industrial Experience (MChem)',
    'Chemistry with International Study (MChem)',
    'Chemistry with Medicinal Chemistry (BSc)',
    'Chemistry with Medicinal Chemistry (MChem)',
    "Children's Nursing (BNurs)",
    'Chinese and English Language (BA)',
    'Chinese and French (BA)',
    'Chinese and German (BA)',
    'Chinese and Japanese (BA)',
    'Chinese and Linguistics (BA)',
    'Chinese and Politics (BA)',
    'Chinese and Russian (BA)',
    'Chinese and Spanish (BA)',
    'Chinese Studies (BA)',
    'Civil and Structural Engineering (MEng)',
    'Civil Engineering (BEng)',
    'Civil Engineering (MEng)',
    'Civil Engineering (Enterprise) (MEng)',
    'Civil Engineering with Industrial Experience (MEng)',
    'Classical Studies (BA)',
    'Classics (BA)',
    'Cognitive Neuroscience and Psychology (BSc)',
    'Comparative Religion and Social Anthropology (BA)',
    'Computer Science (BSc)',
    'Computer Science and Mathematics (BSc)',
    'Computer Science and Mathematics with Industrial Experience (BSc)',
    'Computer Science with Industrial Experience (BSc)',
    'Creative and Cultural Industries (BA)',
    'Criminology (BA)',
    'Criminology and Data Analytics (BASS)',
    'Criminology with International Study (BA)',
    'Dental Hygiene and Therapy (BSc)',
    'Dentistry (first-year entry) (BDS)',
    'Dentistry (pre-dental entry) (BDS)',
    'Development Studies (BAEcon)',
    'Development Studies and Data Analytics (BAEcon)',
    'Digital Media, Culture and Society (BA)',
    'Drama (BA)',
    'Drama and English Literature (BA)',
    'Drama and Film Studies (BA)',
    'Drama and Music (BA)',
    'Earth and Planetary Sciences (BSc)',
    'Earth and Planetary Sciences (MEarthSci)',
    'Earth and Planetary Sciences with a Research Placement (MEarthSci)',
    'Earth and Planetary Sciences with Industrial Experience (MEarthSci)',
    'Earth and Planetary Sciences with International Study (MEarthSci)',
    'East Asian Studies (BA)',
    'East Asian Studies with International Study (BA)',
    'Economics (BAEcon)',
    'Economics (BSc)',
    'Economics and Data Analytics (BAEcon)',
    'Economics and Finance (BAEcon)',
    'Economics and Philosophy (BAEcon)',
    'Economics and Politics (BAEcon)',
    'Economics and Sociology (BAEcon)',
    'Education (BSc)',
    'Education, Leadership and Culture (BA)',
    'Educational Psychology (BSc)',
    'Egyptology (UGCert)',
    'Egyptology (UGDip)',
    'Electrical and Electronic Engineering (BEng)',
    'Electrical and Electronic Engineering (MEng)',
    'Electrical and Electronic Engineering with Industrial Experience (BEng)',
    'Electrical and Electronic Engineering with Industrial Experience (MEng)',
    'Electronic Engineering (BEng)',
    'Electronic Engineering (MEng)',
    'Electronic Engineering with Industrial Experience (BEng)',
    'Electronic Engineering with Industrial Experience (MEng)',
    'English Language (BA)',
    'English Language and Arabic (BA)',
    'English Language and Chinese (BA)',
    'English Language and English Literature (BA)',
    'English Language and French (BA)',
    'English Language and German (BA)',
    'English Language and Japanese (BA)',
    'English Language and Russian (BA)',
    'English Language and Spanish (BA)',
    'English Literature (BA)',
    'English Literature and American Studies (BA)',
    'English Literature and Drama (BA)',
    'English Literature and French (BA)',
    'English Literature and German (BA)',
    'English Literature and History (BA)',
    'English Literature and Italian (BA)',
    'English Literature and Latin (BA)',
    'English Literature and Spanish (BA)',
    'English Literature with Creative Writing (BA)',
    'Environmental Management (BSc)',
    'Environmental Management with Professional Placement (BSc)',
    'Environmental Science (BSc)',
    'Environmental Science (MEnvSci)',
    'Environmental Science with a Research Placement (MEnvSci)',
    'Environmental Science with Industrial Experience (MEnvSci)',
    'Environmental Science with International Study (MEnvSci)',
    'Fashion Buying and Merchandising (BSc)',
    'Fashion Management (BSc)',
    'Fashion Marketing (BSc)',
    'Film Studies and Arabic (BA)',
    'Film Studies and Archaeology (BA)',
    'Film Studies and Chinese (BA)',
    'Film Studies and East Asian Studies (BA)',
    'Film Studies and English Language (BA)',
    'Film Studies and English Literature (BA)',
    'Film Studies and French (BA)',
    'Film Studies and German (BA)',
    'Film Studies and History (BA)',
    'Film Studies and History of Art (BA)',
    'Film Studies and Italian (BA)',
    'Film Studies and Japanese (BA)',
    'Film Studies and Linguistics (BA)',
    'Film Studies and Middle Eastern Studies (BA)',
    'Film Studies and Music (BA)',
    'Film Studies and Portuguese (BA)',
    'Film Studies and Russian (BA)',
    'Film Studies and Spanish (BA)',
    'Finance (BAEcon)',
    'French and Chinese (BA)',
    'French and English Language (BA)',
    'French and German (BA)',
    'French and History (BA)',
    'French and Italian (BA)',
    'French and Japanese (BA)',
    'French and Politics (BA)',
    'French and Portuguese (BA)',
    'French and Russian (BA)',
    'French and Spanish (BA)',
    'French Studies (BA)',
    'Genetics (BSc)',
    'Genetics (MSci)',
    'Genetics with a Modern Language (BSc)',
    'Genetics with Entrepreneurship (BSc)',
    'Genetics with Industrial/Professional Experience (BSc)',
    'Geography (BA)',
    'Geography (BSc)',
    'Geography with International Study (BA)',
    'Geography with International Study (BSc)',
    'Geography with Professional Placement (BA)',
    'Geography with Professional Placement (BSc)',
    'German and Chinese (BA)',
    'German and English Language (BA)',
    'German and French (BA)',
    'German and History (BA)',
    'German and Italian (BA)',
    'German and Japanese (BA)',
    'German and Politics (BA)',
    'German and Portuguese (BA)',
    'German and Russian (BA)',
    'German and Spanish (BA)',
    'German Studies (BA)',
    'Global Development (BSc)',
    'Global Development with International Study (BSc)',
    'Global Health (intercalated) (BSc)',
    'Global Social Challenges (BA)',
    'Healthcare Science (Audiology) (BSc)',
    'History (BA)',
    'History and American Studies (BA)',
    'History and Arabic (BA)',
    'History and Art History (BA)',
    'History and French (BA)',
    'History and German (BA)',
    'History and Italian (BA)',
    'History and Portuguese (BA)',
    'History and Russian (BA)',
    'History and Sociology (BA)',
    'History and Spanish (BA)',
    'History of Art (BA)',
    'Immunology (BSc)',
    'Immunology (MSci)',
    'Immunology with a Modern Language (BSc)',
    'Immunology with Entrepreneurship (BSc)',
    'Immunology with Industrial/Professional Experience (BSc)',
    'Information Technology Management for Business (BSc)',
    'Information Technology Management for Business with Industrial Experience (BSc)',
    'International Business, Finance and Economics (BSc)',
    'International Business, Finance and Economics with Industrial/Professional Experience (BSc)',
    'International Disaster Management & Humanitarian Response (BSc)',
    'International Disaster Management and Humanitarian Response and Arabic (BSc)',
    'International Disaster Management and Humanitarian Response and Chinese (BSc)',
    'International Disaster Management and Humanitarian Response and French (BSc)',
    'International Disaster Management and Humanitarian Response and Spanish (BSc)',
    'International Management (BSc)',
    'Italian and French (BA)',
    'Italian and German (BA)',
    'Italian and History (BA)',
    'Italian and Latin (BA)',
    'Italian and Politics (BA)',
    'Italian and Spanish (BA)',
    'Italian Studies (BA)',
    'Japanese and English Language (BA)',
    'Japanese and French (BA)',
    'Japanese and German (BA)',
    'Japanese and Linguistics (BA)',
    'Japanese and Politics (BA)',
    'Japanese and Russian (BA)',
    'Japanese and Spanish (BA)',
    'Japanese Studies (BA)',
    'Latin and English Literature (BA)',
    'Latin and French (BA)',
    'Latin and Italian (BA)',
    'Latin and Linguistics (BA)',
    'Latin and Spanish (BA)',
    'Law (LLB)',
    'Law with Criminology (LLB)',
    'Law with International Study (LLB)',
    'Law with Politics (LLB)',
    'Liberal Arts (BA)',
    'Liberal Arts with International Study (BA)',
    'Life Sciences (BSc)',
    'Life Sciences with a Modern Language (BSc)',
    'Life Sciences with Entrepreneurship (BSc)',
    'Life Sciences with Industrial/Professional Experience (BSc)',
    'Linguistics (BA)',
    'Linguistics and Arabic (BA)',
    'Linguistics and Chinese (BA)',
    'Linguistics and French (BA)',
    'Linguistics and German (BA)',
    'Linguistics and Italian (BA)',
    'Linguistics and Japanese (BA)',
    'Linguistics and Latin (BA)',
    'Linguistics and Portuguese (BA)',
    'Linguistics and Russian (BA)',
    'Linguistics and Social Anthropology (BA)',
    'Linguistics and Sociology (BA)',
    'Linguistics and Spanish (BA)',
    'Management (BSc)',
    'Management (Accounting & Finance) with Industrial/Professional Experience (BSc)',
    'Management (Accounting and Finance) (BSc)',
    'Management (Human Resources) (BSc)',
    'Management (Human Resources) with Industrial/Professional Experience (BSc)',
    'Management (Innovation, Strategy and Entrepreneurship) (BSc)',
    'Management (Innovation, Strategy and Entrepreneurship) with Industrial / Professional Experience (BSc)',
    'Management (International Business Economics) (BSc)',
    'Management (International Business Economics) with Industrial/Professional Experience (BSc)',
    'Management (Marketing) (BSc)',
    'Management (Marketing) with Industrial/Professional Experience (BSc)',
    'Management with Industrial/Professional Experience (BSc)',
    'Master of Planning with Real Estate (MPRE)',
    'Materials Science and Engineering (BSc)',
    'Materials Science and Engineering (MEng)',
    'Materials Science and Engineering with Biomaterials (MEng)',
    'Materials Science and Engineering with Corrosion (MEng)',
    'Materials Science and Engineering with Metallurgy (MEng)',
    'Materials Science and Engineering with Nanomaterials (MEng)',
    'Materials Science and Engineering with Polymers (MEng)',
    'Materials Science and Engineering with Textiles Technology (MEng)',
    'Mathematics (BSc)',
    'Mathematics (MMath)',
    'Mathematics and Philosophy (BSc)',
    'Mathematics and Physics (BSc)',
    'Mathematics and Physics (MMath&Phys)',
    'Mathematics and Statistics (BSc)',
    'Mathematics and Statistics (MMath)',
    'Mathematics with Finance (BSc)',
    'Mathematics with Placement Year (BSc)',
    'Mechanical Engineering (BEng)',
    'Mechanical Engineering (MEng)',
    'Mechanical Engineering with Industrial Experience (MEng)',
    'Mechanical Engineering with Management (BEng)',
    'Mechanical Engineering with Management (MEng)',
    'Mechatronic Engineering (BEng)',
    'Mechatronic Engineering (MEng)',
    'Mechatronic Engineering with Industrial Experience (BEng)',
    'Mechatronic Engineering with Industrial Experience (MEng)',
    'Medical Biochemistry (BSc)',
    'Medical Biochemistry (MSci)',
    'Medical Biochemistry with Industrial/Professional Experience (BSc)',
    'Medical Physiology (BSc)',
    'Medical Physiology (MSci)',
    'Medical Physiology with a Modern Language (BSc)',
    'Medical Physiology with Entrepreneurship (BSc)',
    'Medical Physiology with Industrial/Professional Experience (BSc)',
    'Medicine (MBChB)',
    'Mental Health Nursing (BNurs)',
    'Microbiology (BSc)',
    'Microbiology (MSci)',
    'Microbiology with a Modern Language (BSc)',
    'Microbiology with Entrepreneurship (BSc)',
    'Microbiology with Industrial/Professional Experience (BSc)',
    'Middle Eastern Studies (BA)',
    'Midwifery (BMidwif)',
    'Modern History and Politics (BA)',
    'Modern History with Economics (BA)',
    'Modern Language and Business & Management (Arabic) (BA)',
    'Modern Language and Business & Management (Chinese) (BA)',
    'Modern Language and Business & Management (French) (BA)',
    'Modern Language and Business & Management (German) (BA)',
    'Modern Language and Business & Management (Italian) (BA)',
    'Modern Language and Business & Management (Japanese) (BA)',
    'Modern Language and Business & Management (Portuguese) (BA)',
    'Modern Language and Business & Management (Russian) (BA)',
    'Modern Language and Business & Management (Spanish) (BA)',
    'Molecular Biology (BSc)',
    'Molecular Biology (MSci)',
    'Molecular Biology with a Modern Language (BSc)',
    'Molecular Biology with Entrepreneurship (BSc)',
    'Molecular Biology with Industrial/Professional Experience (BSc)',
    'Music (MusB)',
    'Music and Drama (BA)',
    'Neuroscience (BSc)',
    'Neuroscience (MSci)',
    'Neuroscience with a Modern Language (BSc)',
    'Neuroscience with Entrepreneurship (BSc)',
    'Neuroscience with Industrial/Professional Experience (BSc)',
    'Nursing (BNurs)',
    'Optometry (MSci)',
    'Pharmacology (BSc)',
    'Pharmacology (MSci)',
    'Pharmacology with a Modern Language (BSc)',
    'Pharmacology with Entrepreneurship (BSc)',
    'Pharmacology with Industrial/Professional Experience (BSc)',
    'Pharmacy (MPharm)',
    'Philosophy (BA)',
    'Philosophy and Criminology (BASS)',
    'Philosophy and Data Analytics (BASS)',
    'Philosophy and Politics (BASS)',
    'Philosophy and Religion (BA)',
    'Physics (BSc)',
    'Physics (MPhys)',
    'Physics with Astrophysics (BSc)',
    'Physics with Astrophysics (MPhys)',
    'Physics with Study in Europe (MPhys)',
    'Physics with Theoretical Physics (BSc)',
    'Physics with Theoretical Physics (MPhys)',
    'Planning (MPlan)',
    'Planning and Real Estate (BSc)',
    'Planning and Real Estate with Professional Placement (BSc)',
    'Planning and Real Estate with Professional Placement (MPRE)',
    'Planning with Professional Placement (MPlan)',
    'Politics, Philosophy and Economics (BA)',
    'Politics and Arabic (BA)',
    'Politics and Chinese (BA)',
    'Politics and Criminology (BASS)',
    'Politics and Data Analytics (BASS)',
    'Politics and French (BA)',
    'Politics and German (BA)',
    'Politics and International Relations (BSocSc)',
    'Politics and Italian (BA)',
    'Politics and Japanese (BA)',
    'Politics and Modern History (BA)',
    'Politics and Portuguese (BA)',
    'Politics and Russian (BA)',
    'Politics and Social Anthropology (BASS)',
    'Politics and Sociology (BASS)',
    'Politics and Spanish (BA)',
    'Portuguese and French (BA)',
    'Portuguese and German (BA)',
    'Portuguese and History (BA)',
    'Portuguese and Linguistics (BA)',
    'Portuguese and Politics (BA)',
    'Portuguese and Spanish (BA)',
    'Psychology (BSc)',
    'Public Health (BSc)',
    'Religions, Theology and Ethics (BA)',
    'Russian and Chinese (BA)',
    'Russian and English Language (BA)',
    'Russian and French (BA)',
    'Russian and German (BA)',
    'Russian and History (BA)',
    'Russian and Japanese (BA)',
    'Russian and Linguistics (BA)',
    'Russian and Politics (BA)',
    'Russian and Spanish (BA)',
    'Russian Studies (BA)',
    'Social Anthropology (BSocSc)',
    'Social Anthropology and Criminology (BASS)',
    'Social Anthropology and Data Analytics (BASS)',
    'Social Anthropology and Linguistics (BA)',
    'Social Anthropology and Philosophy (BASS)',
    'Social Anthropology and Sociology (BASS)',
    'Sociology (BSocSc)',
    'Sociology and Arabic (BA)',
    'Sociology and Chinese (BA)',
    'Sociology and Criminology (BASS)',
    'Sociology and Data Analytics (BASS)',
    'Sociology and French (BA)',
    'Sociology and German (BA)',
    'Sociology and History (BA)',
    'Sociology and Italian (BA)',
    'Sociology and Japanese (BA)',
    'Sociology and Linguistics (BA)',
    'Sociology and Philosophy (BASS)',
    'Sociology and Portuguese (BA)',
    'Sociology and Russian (BA)',
    'Sociology and Spanish (BA)',
    'Spanish, Portuguese and Latin American Studies (BA)',
    'Spanish and Chinese (BA)',
    'Spanish and English Language (BA)',
    'Spanish and French (BA)',
    'Spanish and German (BA)',
    'Spanish and History (BA)',
    'Spanish and Italian (BA)',
    'Spanish and Japanese (BA)',
    'Spanish and Latin (BA)',
    'Spanish and Linguistics (BA)',
    'Spanish and Politics (BA)',
    'Spanish and Portuguese (BA)',
    'Spanish and Russian (BA)',
    'Speech and Language Therapy (BSc)',
    'Zoology (BSc)',
    'Zoology (MSci)',
    'Zoology with a Modern Language (BSc)',
    'Zoology with Entrepreneurship (BSc)',
    'Zoology with Industrial/Professional Experience (BSc)',
    'POSTGRADUATE COURSES',
    'Accounting (MSc)',
    'Accounting and Finance (MSc)',
    'ACS: Artificial Intelligence (MSc)',
    'ACS: Computer Security (MSc)',
    'ACS: Data and Knowledge Management (MSc)',
    'ACS: Digital Biology (MSc)',
    'Adult Nursing (MSc)',
    'Advanced Audiology Studies (MSc/PGDip)',
    'Advanced Chemical Engineering (MSc)',
    'Advanced Clinical Optometric Practice (MSc)',
    'Advanced Clinical Practice (MSc)',
    'Advanced Computer Science (MSc)',
    'Advanced Control and Systems Engineering (MSc)',
    'Advanced Electrical Power Systems Engineering (MSc)',
    'Advanced Engineering Materials (MSc)',
    'Advanced Leadership for Professional Practice (MSc)',
    'Advanced Manufacturing Technology & Systems Management (MSc)',
    'Advanced Process Integration and Design (MSc)',
    'Aerospace Engineering (MSc)',
    'Analytical Chemistry and Measurement Science (MSc/PGDip/PGCert)',
    'Anthropological Research (MA)',
    'Applied Mathematics (MSc)',
    'Architecture (MArch)',
    'Architecture and Adaptive Reuse (MA)',
    'Architecture and Urbanism (MA)',
    'Art Gallery and Museum Studies (MA)',
    'Arts Management, Policy and Practice (MA)',
    'Audiology (MSc)',
    'Biochemistry (MSc)',
    'Bioinformatics and Systems Biology (MSc)',
    'Biological Sciences (MSc)',
    'Biomaterials (MSc)',
    'Biotechnology and Enterprise (MSc)',
    'Business Analysis and Strategic Management (MSc)',
    'Business Analytics (MSc)',
    'Business Psychology (MSc)',
    'Cancer Research and Molecular Biomedicine (MSc)',
    'Cardiovascular Health and Disease (MSc)',
    'Cell Biology (MSc)',
    'Chemistry (MSc)',
    'Classics and Ancient History (MA)',
    'Climate Change (MSc)',
    'Clinical and Health Psychology (MSc)',
    'Clinical Biochemistry (MSc)',
    'Clinical Data Science (MSc)',
    'Clinical Dentistry (MSc)',
    'Clinical Immunology (MSc)',
    'Clinical Pharmacy (MSc)',
    'Clinical Research (MClin Res)',
    'Cognitive Neuroscience and Neuropsychology (MRes)',
    'Commercial Project Management (MSc)',
    'Communications and Signal Processing (MSc)',
    'Composition (MusM)',
    'Computational and Corpus Linguistics (MSc)',
    'Construction Project Management (MSc)',
    'Corporate Governance (LLM)',
    'Corrosion Control Engineering (MSc)',
    'Creative and Cultural Industries (MA)',
    'Creative Writing (MA)',
    'Criminology (MA)',
    'Data Analytics and Social Statistics (MSc/PGDip)',
    'Data Science (MSc)',
    'Deaf Education (MSc/PGDip)',
    'Development Economics and Policy (MSc)',
    'Development Finance (MSc)',
    'Developmental Biology (MSc)',
    'Digital Development (MSc)',
    'Digital Marketing (MSc)',
    'Digital Media, Culture and Society (MA)',
    'Digital Technologies, Communication and Education (MA)',
    'Economics (MA)',
    'Economics (MSc)',
    'Economics and Data Science (MSc)',
    'Education for a Sustainable Environment (MA)',
    'Educational Leadership (MA)',
    'Egyptology (MA)',
    'Electrical Power Systems Engineering (MSc)',
    'Endodontics (MSc)',
    'Engineering Project Management (MSc)',
    'English Literature and American Studies (MA)',
    'Environmental Governance (MSc)',
    'Environmental Impact Assessment & Management (MSc)',
    'Environmental Monitoring, Modelling and Reconstruction (MSc)',
    'Experimental Psychology with Data Science (MRes)',
    'Film Studies (MA)',
    'Finance (MSc)',
    'Financial Crime and Compliance in Digital Societies (MSc)',
    'Financial Economics (MSc)',
    'Financial Management (MSc)',
    'Fixed and Removable Prosthodontics (MSc)',
    'Forensic Psychology and Mental Health (MSc)',
    'Gender, Sexuality and Culture (MA/PGDip)',
    'Genomic Medicine (MSc)',
    'Geographical Information Science (MSc)',
    'Geoscience for Sustainable Energy (MSc)',
    'Global Development (MSc)',
    'Global Executive MBA (MBA)',
    'Global Health (MSc)',
    'Global Urban Development and Planning (MSc)',
    'Green Infrastructure (MSc)',
    'Health and Social Care (MRes/PGDip/PGCert)',
    'Health Data Science (MSc)',
    'Health Informatics (MSc/PGDip/PGCert)',
    'Health Psychology (MSc)',
    'Healthcare Ethics and Law (LLM)',
    'Healthcare Ethics and Law (MA)',
    'Healthcare Ethics and Law (MSc)',
    'Healthcare Ethics and Law (LLM)',
    'Healthcare Ethics and Law (MA)',
    'Healthcare Ethics and Law (PGDip)',
    'Healthcare Ethics (PGCert)',
    'Healthcare Law (PGCert)',
    'Heritage Studies (MA/PGDip)',
    'History (MA)',
    'History of Science, Technology and Medicine (MA)',
    'Human Resource Development (MSc)',
    'Human Resource Management (MSc)',
    'Human Resource Management and Industrial Relations (MSc)',
    'Human Rights (MA)',
    'Humanitarian Practice (MSc/PGDip/PGCert)',
    'Humanitarianism and Conflict Response (MA)',
    'Infection Biology (MSc)',
    'Innovation Management and Entrepreneurship (MSc)',
    'Intellectual Property Law (LLM)',
    'Intercultural Communication (MA)',
    'International Business and Commercial Law (LLM)',
    'International Business and Management (MSc)',
    'International Commercial and Technology Law (LLM)',
    'International Development (MSc)',
    'International Disaster Management (MSc)',
    'International Economic Law (LLM)',
    'International Education (MA)',
    'International Fashion Marketing (MSc)',
    'International Fashion Retailing (MSc)',
    'International Financial Law (LLM)',
    'International Human Resource Management and Comparative Industrial Relations (MSc)',
    'International Political Economy (MA)',
    'International Relations (MA)',
    'Investigative Ophthalmology and Vision Science (MSc)',
    'Law (LLM)',
    'Library and Archive Studies (MA)',
    'Linguistics (MA)',
    'Management (MRes)',
    'Management (MSc)',
    'Management and Implementation of Development Projects (MSc)',
    'Management and Information Systems: Change and Development (MSc)',
    'Management of Projects (MSc)',
    'Marketing (MSc)',
    'Mathematical Finance (MSc)',
    'Mechanical Engineering Design (MSc)',
    'Medical and Molecular Virology (MSc)',
    'Medical Imaging Science (MSc)',
    'Medical Microbiology (MSc)',
    'Medical Sciences (MRes)',
    'Medieval and Early Modern Studies (MA)',
    'Modern and Contemporary Literature (MA)',
    'Modern Languages and Cultures (MA)',
    'Molecular Pathology of Cancer (MSc)',
    'Music (MusM)',
    'Nanomaterials (MSc)',
    'Nanomedicine by Research (MSc)',
    'Neuroimaging for Clinical & Cognitive Neuroscience (MSc)',
    'Neuroscience (MSc)',
    'Nuclear Science and Technology (MSc)',
    'Occupational Health (MPH)',
    'Occupational Hygiene (MSc)',
    'Occupational Medicine (MSc)',
    'Oncology Research (MSc)',
    'Operations, Project and Supply Chain Management (MSc)',
    'Oral and Maxillofacial Surgery (MSc)',
    'Oral Health & Disease in Populations (CPD)',
    'Organisational Change and Development (MSc)',
    'Organisational Psychology (MSc)',
    'Orthodontics (MSc)',
    'Peace and Conflict Studies (MA)',
    'Periodontology (MSc)',
    'Personal Professional Development (PG credit)',
    'Petroleum Geoscience (MSc)',
    'PGCE Primary (PGCE)',
    'PGCE Primary School Direct 5-11 (PGCE)',
    'PGCE Secondary Biology (PGCE)',
    'PGCE Secondary Business Education (PGCE)',
    'PGCE Secondary Chemistry (PGCE)',
    'PGCE Secondary Economics and Business Education (PGCE)',
    'PGCE Secondary English (PGCE)',
    'PGCE Secondary French (PGCE)',
    'PGCE Secondary Geography (PGCE)',
    'PGCE Secondary German (PGCE)',
    'PGCE Secondary History (PGCE)',
    'PGCE Secondary Mathematics (PGCE)',
    'PGCE Secondary Mathematics with Economics (PGCE)',
    'PGCE Secondary Physics (PGCE)',
    'PGCE Secondary Physics with Maths (PGCE)',
    'PGCE Secondary School Direct (English) (PGCE)',
    'PGCE Secondary School Direct (French) (PGCE)',
    'PGCE Secondary School Direct (Geography) (PGCE)',
    'PGCE Secondary School Direct (German) (PGCE)',
    'PGCE Secondary School Direct (History) (PGCE)',
    'PGCE Secondary School Direct (Mathematics) (PGCE)',
    'PGCE Secondary School Direct (Spanish) (PGCE)',
    'PGCE Secondary School Direct Science: Biology (PGCE)',
    'PGCE Secondary School Direct Science: Chemistry (PGCE)',
    'PGCE Secondary School Direct Science: Physics (PGCE)',
    'PGCE Secondary School Direct: Business Education (PGCE)',
    'PGCE Secondary Spanish (PGCE)',
    'Pharmaceutical Technology and Quality Assurance (MSc)',
    'Philosophy (MA)',
    'Physician Associate Studies (MSc)',
    'Planning (MSc)',
    'Playwriting (MA)',
    'Political Economy (MA)',
    'Political Science - Democracy and Elections (MA)',
    'Political Science - European Politics & Policy Pathway (MA)',
    'Political Science - Governance and Public Policy Pathway (MA)',
    'Political Science - Philosophy and Political Theory (MA)',
    'Political Science - Political Theory Pathway (MA)',
    'Politics (MA)',
    'Pollution & Environmental Control (MSc)',
    'Pollution and Environmental Control (MSc)',
    'Polymer Materials Science and Engineering (MSc)',
    'Precision Medicine (MSc)',
    'Primary Care (MRes)',
    'Primary Mental Health Care pathway - APIMH (MSc/PGDip)',
    'Psychology of Education (MEd)',
    'Public Health (MPH)',
    'Public Health (MRes)',
    'Public International Law (LLM)',
    'Pure Mathematics (MSc)',
    'Pure Mathematics and Mathematical Logic (MSc)',
    'Quantitative Finance (MSc)',
    'Real Estate (MSc)',
    'Real Estate Asset Management (MSc)',
    'Real Estate Development (MSc)',
    'Real Estate Finance and Investment (MSc)',
    'Reliability Engineering and Asset Management (MSc)',
    'Religions and Theology (MA)',
    'Renewable Energy and Clean Technology (MSc)',
    'Reproduction and Pregnancy (MSc)',
    'Research Methods with Education (MSc)',
    'Research Methods with Human Geography (MSc)',
    'Research Methods with International Development (MSc)',
    'Research Methods with Planning and Environmental Management (MSc)',
    'Robotics (MSc)',
    'Science and Health Communication (MSc)',
    'Screenwriting (MA)',
    'Secondary School Direct Economics and Business Education 14-19 (PGCE)',
    'Security and International Law (LLM)',
    'Skin Ageing and Aesthetic Medicine (MSc)',
    'Social Anthropology (MA)',
    'Social Change, Environment and Sustainability (MA)',
    'Social Network Analysis (MSc)',
    'Social Research Methods and Statistics (MSc)',
    'Social Work (MA)',
    'Sociological Research (MSc)',
    'Sociology (MA)',
    'Specialist Practice (Cancer) (MSc)',
    'Speech & Language (CPD)',
    'Statistics (MSc)',
    'Structural Engineering (MSc)',
    'Subsurface Energy Engineering (MSc)',
    'Sustainable Business (MSc)',
    'Sustainable Electrical Power Systems Engineering (MSc/PGDip/PGCert)',
    'TESOL (MA)',
    'Textile Technology (MSc)',
    'Thermal Power & Fluid Engineering (MSc)',
    'Tissue Engineering for Regenerative Medicine (MSc)',
    'Translation and Interpreting Studies (MA)',
    'Transnational Dispute Resolution (LLM)',
    'Urban Design and International Planning (MSc)',
    'Urban Regeneration and Development (MSc)',
    'Urban Studies (MSc)',
    'Visual Anthropology (MA)',
  ];

  async findAll(): Promise<string[]> {
    return this.courses;
  }

  async findBySearch(search: string): Promise<string[]> {
    return this.courses.filter((course) =>
      course.toLowerCase().includes(search.toLowerCase()),
    );
  }
}
